services:
  - type: web
    name: xingyi-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    rootDirectory: server
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
